name: data_analysis
dependencies:
- python=3.6
- cython
- dask
- ipython
- jupyter
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- line_profiler
- nose_parameterized
- numpy
- pandas>=0.18.1
- scikit-learn>=0.18.1
- scipy>=0.17.1
- seaborn>=0.7.0
- snakeviz
- sympy
- xlrd
- pip:
    - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3